-- BE-15-1: personalized feedback (reflection + weak points + recommended practices).
-- Run before deploying the BE-15 backend code. One feedback row per task (idempotent).
--
-- weak_points / recommendations store JSON string arrays; raw_payload keeps the
-- source validation_finished payload for traceability. When no reflection event is
-- available the row is generated by local rules and source = 'RULE_FALLBACK'.

CREATE TABLE IF NOT EXISTS `ai_feedback` (
  `id` varchar(32) NOT NULL COMMENT 'Feedback row ID',
  `task_id` varchar(32) NOT NULL COMMENT 'LingXi task ID (one feedback per task)',
  `conversation_id` varchar(32) NULL COMMENT 'LingXi conversation ID',
  `user_id` varchar(32) NOT NULL COMMENT 'Owner customer ID',
  `summary` varchar(1024) NULL COMMENT 'Reflection conclusion / summary',
  `weak_points` json NULL COMMENT 'Weak knowledge points (JSON string array)',
  `recommendations` json NULL COMMENT 'Recommended practices (JSON string array)',
  `next_step` varchar(512) NULL COMMENT 'Suggested next step',
  `source` varchar(32) NOT NULL DEFAULT 'RULE_FALLBACK' COMMENT 'VALIDATION_FINISHED or RULE_FALLBACK',
  `raw_payload` json NULL COMMENT 'Source validation_finished payload for traceability',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_feedback_task` (`task_id`),
  KEY `idx_ai_feedback_user_created` (`user_id`, `created_at`),
  KEY `idx_ai_feedback_conversation` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI personalized feedback';
